name: Build and Test Spring Boot App

on:
  workflow_dispatch:
  # Uncomment these if you want to trigger on push/PR
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package

      - name: Run tests
        run: mvn test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          sonar.projectKey: samsharma_code-with-quarkus
          sonar.organization: samsharma-github
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Upload JAR to S3
        run: |
          FILE=$(find target -type f -name "*.jar" | head -n 1)
          if [ -z "$FILE" ]; then
            echo "❌ JAR file not found. Failing the job."
            exit 1
          fi
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          FILENAME=$(basename "$FILE")
          echo "Uploading $FILENAME to S3 bucket..."
          aws s3 cp "$FILE" "s3://mrsamsharma777/builds/${TIMESTAMP}-${FILENAME}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
