name: Build and Test Spring Boot App

on:
  workflow_dispatch:
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package

      - name: Run tests
        run: mvn test
      - name: Upload JAR to S3
        run: |
          FILE=$(find target -type f -name "*.jar" | head -n 1)
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          FILENAME=$(basename "$FILE")
          aws s3 cp "$FILE" "s3://mrsamsharma777/builds/${TIMESTAMP}-${FILENAME}"
        env:
          # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: AKIATOWGB6NWJG4WXT2Q
          AWS_SECRET_ACCESS_KEY: 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
          AWS_DEFAULT_REGION: us-east-1
